"""add address model

Revision ID: 257638e1803d
Revises: c1bb3afdb9d5
Create Date: 2025-09-11 11:42:49.005668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '257638e1803d'
down_revision: Union[str, Sequence[str], None] = 'c1bb3afdb9d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('realname', sa.String(length=200), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    # ### end Alembic commands ###
