"""init database

Revision ID: 7650166158e5
Revises: 
Create Date: 2025-09-12 14:29:44.024563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7650166158e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=300), nullable=True),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.Column('is_activate', sa.Boolean(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=True)
    op.create_table('address',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('realname', sa.String(length=200), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    op.drop_index(op.f('ix_users_mobile'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
